<?xml version="1.0" standalone="yes"?>
<!DOCTYPE goals [
	<!ELEMENT goals (category*)>
	<!ELEMENT category (goal+)>
	<!ATTLIST category name CDATA #REQUIRED>
	<!ELEMENT goal (description?, prereqs?)>
	<!ATTLIST goal name CDATA #REQUIRED>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT prereqs (prereq*)>
	<!ELEMENT prereq (#PCDATA)>
	<!ATTLIST prereq goal CDATA #REQUIRED>
]>
<goals>
	<category name="eclipse">
		<goal name="generate-project">
			<description>Generate Eclipse .project and .classpath project files</description>
			<prereqs/>
		</goal>
		<goal name="add-maven-repo">
			<description>Ensure that the classpath variable MAVEN_REPO is available</description>
			<prereqs/>
		</goal>
		<goal name="get-goals">
			<description>Get all the available goals</description>
			<prereqs/>
		</goal>
		<goal name="external-tools">
			<description>Generate an Eclipse external tool for each goal</description>
			<prereqs/>
		</goal>
		<goal name="(default)">
			<description>Generate Eclipse project files</description>
			<prereqs>
				<prereq goal="eclipse:generate-project"/>
			</prereqs>
		</goal>
	</category>
</goals>